### PR TITLE
port to sdl2

### PR DESCRIPTION
**Pull request by gsathya**
Builds fine. Not sure how to run this though -- none of my ROMs seem to work (with the master branch even).

### CODE REVIEW

**Comment by gsathya** [comment]
Hmm, the arrow keys don't work any more. Need to change the mapping based on https://wiki.libsdl.org/SDLKeycodeLookup.

**Comment by gsathya** [comment]
ported opengl_video.c to use sdl2

**Comment by sronsse** [comment]
Also, I noticed you use #include SDL2/SDL.h instead of #include SDL.h. The latter is preferred considering that the pkg-config flags file which comes with the library already has a -I${includedir}/SDL2 C flag. I've noticed quite a bunch of whitespace errors but I can fix it when I will merge in master later. Thanks!

**Comment by sronsse** [comment]
Alright, I guess it's never too late right :) Thanks @gsathya, I took your code, updated it a bit, and now the project only uses SDL2.

**Comment by gsathya** [comment]
:+1:

**Pull request closed without merging**
